### ISSUE TITLE
Interface support

### ISSUE THREAD

**Issue by haoyunfeix** [01org/widl-nan#23]
This is an umbrella bug to track support of interface described at https://www.w3.org/TR/WebIDL/#idl-interfaces

- [ ] #2 Exception support
- [ ] #3 Dictionary support

- [ ] #4 Typedef support

- [ ] #5 Array type support

- [ ] #6 static operation support

- [ ] #10 Date support

- [ ] #15 ArrayBuffer support

- [ ] #18 Event listener support
