### ISSUE TITLE
Create trybot/buildbot machanism

### ISSUE THREAD

**Issue by haoyunfeix** [01org/widl-nan#24]
This is an umbrella bug to create trybot/buildbot mechanism for widl-nan,

- [ ] #12 Create trybot/buildbot for Linux

- [ ] #13 Create trybot/buildbot for MacOS

- [ ] #14 Create trybot/buildbot for Windows

**Comment by kenny-y** [comment]
@baleboy It looks like to enable travis, there are some operations that have to be done by whom with admin privilege, I believe you're the proper contact to ask. Would you please do us a favor and do the followings (steps copied from similar Crosswalk JIRA). Thanks very much :)


1. Visit https://github.com
1. Login github with admin permission of otcshare/widl-nan
1. Create a SSH key pair *w/o passphrase* (required by Travis) and import into account settings.


Then, visit https://travis-ci.com


1. Connect with above github account
1. Toggle otcshare/widl-nan project.
1. Click the settings (right side of the toggle button in step 3), toggle "Build only if .travis.yml is present".
Add the non passphrase SSH private key

Then all should works. For more information, please refer to https://docs.travis-ci.com/user/travis-pro/

**Comment by halton** [comment]
@kenny-y above is private repo steps. For public repos, a little bit easier (no need SSH key). 
1. Visit https://travis-ci.org (not travis-ci.com)
2. Toggle 01org/widl-nan project.
2. Click the settings (right side of the toggle button in step 3), toggle "Build only if .travis.yml is present".

**Comment by halton** [comment]
@baleboy could you do that because you have admin permission.

**Comment by baleboy** [comment]
OK, I "flipped the switch" in travis-ci.org

**Comment by halton** [comment]
@baleboy now the trybot/buildbot (Linux/Mac) are working, thanks a lot.

I'm going to close this issue and the sub-issue for Linux/Mac, leave the windows one open.

BTW, the #50 may cause the wrong alarm of trybot and buildbot, and need to restart before #50 get fixed. @kenny-y @ningxinhu please be noted.
