### ISSUE TITLE
Toolchain: WebIDL generator support for Node Addon

### ISSUE THREAD

**Issue by haoyunfeix** [01org/widl-nan#27]
Developing node addon (https://nodejs.org/api/addons.html) it kind of too raw for developers, lots of duplicated and pattern code need to be written by manually. Nan (https://github.com/nodejs/nan) helps, but not enough
Same as Blink Web IDL generator (https://www.chromium.org/developers/design-documents/idl-compiler), there is need to support WebIDL generator support for Node Addon codes. So that to allow allows developers focus on spec definition and actual implementation logic.

- [ ] #25 Open source PDT

- [ ] #24 Create trybot/buildbot machanism

- [ ] #23 Interface support

- [ ] #11 npmjs.com publishing
